# Generated by Django 2.0.5 on 2018-05-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0004_botheartbeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botheartbeat',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='bot',
            name='last_nonce',
            field=models.BigIntegerField(default=0),
        ),
    ]
