# Generated by Django 2.0.5 on 2018-05-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0005_auto_20180510_2112"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="overwatch.Bot"
                    ),
                ),
            ],
            options={"ordering": ["-time"],},
        ),
    ]
