# Generated by Django 2.0.5 on 2018-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0006_boterror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='base',
            field=models.CharField(help_text='The base currency of the pair', max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='exchange',
            field=models.CharField(help_text='The exchange the bot operates on. Together with the name this forms a unique identifier for this bot', max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(help_text='Name to identify this bot. Usually the name of the pair it operates on', max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='peg',
            field=models.CharField(help_text='The currency to peg to', max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='quote',
            field=models.CharField(help_text='The quote currency of the pair', max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='track',
            field=models.CharField(help_text='The currency to track. This determines if the pair is reversed or not', max_length=255),
        ),
    ]
