# Generated by Django 2.0.5 on 2018-05-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0006_merge_20180510_2114"),
        ("overwatch", "0007_auto_20180514_2030"),
    ]

    operations = []
