# Generated by Django 2.0.5 on 2018-07-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0009_bot_logs_group'),
        ('overwatch', '0009_merge_20180702_2251'),
    ]

    operations = [
    ]
