# Generated by Django 2.1 on 2018-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0013_auto_20180917_1936"),
    ]

    operations = [
        migrations.RemoveField(model_name="botprice", name="side",),
        migrations.AddField(
            model_name="botprice",
            name="ask_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botprice",
            name="ask_price_usd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botprice",
            name="bid_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botprice",
            name="bid_price_usd",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
