# Generated by Django 2.1 on 2018-12-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0020_bottrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottrade',
            options={'ordering': ['-time']},
        ),
        migrations.AlterUniqueTogether(
            name='bottrade',
            unique_together={('bot', 'trade_id')},
        ),
    ]
