# Generated by Django 2.1 on 2019-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0025_auto_20190102_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottrade',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
