# Generated by Django 2.1 on 2019-01-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0026_bottrade_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='aws_region',
            field=models.CharField(default='eu-west-1', max_length=255),
        ),
    ]
