# Generated by Django 2.1.5 on 2019-05-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0029_bot_price_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot", old_name="price_url", new_name="base_price_url",
        ),
        migrations.AddField(
            model_name="bot",
            name="market_price",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bot",
            name="quote_price_url",
            field=models.URLField(
                default="https://price-aggregator.crypto-daio.co.uk/price"
            ),
        ),
    ]
