# Generated by Django 2.1.5 on 2019-05-06 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("overwatch", "0030_auto_20190505_1916"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot", name="active", field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
