# Generated by Django 2.1.5 on 2019-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0031_auto_20190506_2222"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprice",
            name="market_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botprice",
            name="market_price_usd",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
