# Generated by Django 2.1.5 on 2019-11-22 23:37

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0036_bot_bot_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['name', 'exchange', 'active']},
        ),
        migrations.AlterField(
            model_name='bot',
            name='vigil_funds_alert_channel_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Use for reporting fund errors via Vigil.\nDatabase encrypted', null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='vigil_wrapper_error_channel_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Use for reporting bot errors via Vigil.\nDatabase encrypted', null=True),
        ),
    ]
