# Generated by Django 2.1.5 on 2019-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0039_auto_20191206_2048"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="market",
            field=models.CharField(
                default="", help_text="The Market to operate on", max_length=255
            ),
            preserve_default=False,
        ),
    ]
