# Generated by Django 2.1.5 on 2019-12-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0044_auto_20191209_2014"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="peg_price_url",
            field=models.URLField(
                default="https://price-aggregator.crypto-daio.co.uk/price"
            ),
        ),
    ]
