# Generated by Django 2.0.5 on 2018-05-10 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='api_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
