# Generated by Django 2.0.5 on 2018-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0002_bot_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='last_nonce',
            field=models.IntegerField(default=0),
        ),
    ]
