# Generated by Django 2.0.5 on 2018-05-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0003_bot_last_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotHeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversight.Bot')),
            ],
        ),
    ]
