# Generated by Django 2.0.5 on 2018-05-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0005_auto_20180510_1429'),
        ('oversight', '0005_auto_20180510_2112'),
    ]

    operations = [
    ]
