# Generated by Django 2.0.5 on 2018-07-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0008_merge_20180514_2033'),
        ('oversight', '0008_apiprofile'),
    ]

    operations = [
    ]
